//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approvenft
    {
        public int Id { get; set; }
        public int DeployedNFTId { get; set; }
        public string FromAddress { get; set; }
        public string ToCurrentOwnerAddress { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> createDateTime { get; set; }
        public Nullable<System.DateTime> updateDatetime { get; set; }
    
        public virtual deployednft deployednft { get; set; }
    }
}
