//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class deployednft
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deployednft()
        {
            this.Approvenfts = new HashSet<Approvenft>();
            this.NFTLedgers = new HashSet<NFTLedger>();
        }
    
        public int Id { get; set; }
        public int ItemId { get; set; }
        public string ABI { get; set; }
        public Nullable<decimal> GasPrice { get; set; }
        public System.DateTime DeployedDatetime { get; set; }
        public string TransactionHash { get; set; }
        public string ContractAddress { get; set; }
        public string OwnerWalletAddress { get; set; }
        public bool IsVerified { get; set; }
        public bool IsApproved { get; set; }
        public bool IsSold { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approvenft> Approvenfts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NFTLedger> NFTLedgers { get; set; }
        public virtual Item Item { get; set; }
    }
}
