//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFT.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NFTProjectEntities : DbContext
    {
        public NFTProjectEntities()
            : base("name=NFTProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<NFTLedger> NFTLedgers { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Approvenft> Approvenfts { get; set; }
        public virtual DbSet<deployednft> deployednfts { get; set; }
    }
}
